#include <exception>

namespace boost
{
    void throw_exception(std::exception const&) {}
}
